---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

verifier:
  name: inspec
  sudo: true

suites:
  - name: default
    run_list:
      - role[supply_chain_utility]
      - role[supply_chain_utility_deployment]
      - role[supply_chain]
      - recipe[ohai]
      - recipe[nginx::source]
      - recipe[apps-nginx::default]
    attributes:
